#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Info',  url: 'info'}

#-------------------------------
# Projects Section

projects:
- {name: 'GitHub Sponsors Landing Page', url: 'github-sponsors-landing-page', categories: 'product brand'}
- {name: 'Tamagotchi', url: 'tamagotchi', categories: 'illustration'}
- {name: 'Cyberdecks', url: 'cyberdecks', categories: 'illustration'}
- {name: 'Kitchen mural', url: 'kitchen-mural', categories: 'illustration'}
- {name: 'Gartarot', url: 'gartarot', categories: 'illustration'}
- {name: 'Dispo Cam', url: 'dispo-cam', categories: 'product illustration brand'}
- {name: 'Engineering prints', url: 'engineering-prints', categories: 'product illustration brand frontend'}
- {name: 'Apple Juice Box Illustration', url: 'apple-juicebox-illustration', categories: 'illustration industrial'}
- {name: 'Iris Lens', url: 'iris-smartphone-lens', categories: 'brand illustration'}
- {name: 'Friendly Cargo Theme', url: 'friendly-cargo-theme', categories: 'brand frontend'}
- {name: 'Coop website', url: 'coop-website', categories: 'brand frontend'}
- {name: 'Fresh Cookie Scent', url: 'fresh-cookie-scent', categories: 'brand illustration'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/ddddarby'}
- {icon: 'github',    link: 'https://github.com/dthoma1'}
- {icon: 'envelope',  link: ''}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Darby Thomas product design portfolio'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
